// data.js
const BRIEFS = [
  // ════════════════════════════════════════════════════
  // PILLAR 1: KÝ ỨC VẬT THỂ & GIÁC QUAN
  // ════════════════════════════════════════════════════
  {
    id: 1, pillar: "P1",
    title: "Unboxing Hộp Cờ Cũ – Mở Nắp Là Nhớ",
    format: "Video – ASMR / Sound-led",
    formatTag: "VIDEO",
    desc: "Tiếng giở trang giấy báo, xúc xắc lắc trong hộp, quân cờ kim loại đặt xuống. Các âm thanh vật lý dần chuyển mượt sang âm thanh in-game. Zero text, 100% âm thanh. Nhắm audience dùng headphone. Kết thúc: màn hình game hiện ra từ trong lòng chiếc hộp.",
    source: ["Claude"],
    note: "Dùng sound design làm hero, không cần thoại.",
  },
  {
    id: 2, pillar: "P1",
    title: "ASMR Đếm Tiền Giấy Cũ",
    format: "Video – ASMR / Sound-led",
    formatTag: "VIDEO",
    desc: "Cận cảnh bàn tay đang vuốt phẳng tờ 50 Đô-la giấy nhàu từ hộp bánh quy. Tiếng giấy sột soạt, tiếng đếm tiền 'xẹt xẹt'. Chuyển sang game mobile, tiền ảo bay mượt. Message: Cảm giác cũ, công nghệ mới.",
    source: ["DeepSeek"],
    note: "Focus vào texture cảm giác tờ tiền polymer giả.",
  },
  {
    id: 3, pillar: "P1",
    title: "Vật Thể Tuổi Thơ – Object Macro Montage",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Cận cảnh từng vật thân thuộc: cặp sách, hộp bút, dép lê, quạt bàn, radio, snack cũ, hộp bánh quy. Mỗi vật là một emotional cue. Text overlay ngắn. Cuối: 'Ký ức đó giờ nằm trong app này.' Camera macro giữ chất lượng hình ảnh đẹp.",
    source: ["ChatGPT", "Claude"],
    note: "Overlap nhẹ — ChatGPT là macro montage vật thể, Claude focus tờ tiền/quân cờ. Gộp lại thành một brief rộng hơn.",
  },
  {
    id: 4, pillar: "P1",
    title: "Stop Motion Quân Cờ Tự Chế",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Cảnh bàn cờ giấy đầy bụi, quân cờ bị mất. Người chơi lấy nắp chai bia Sài Gòn, cục tẩy, con vụ thay thế. Stop motion hài hước. Chuyển cảnh: trong game, tài sản vẫn là toà nhà lấp lánh nguyên vẹn. Message: Không còn mất quân, không còn chắp vá.",
    source: ["DeepSeek"],
    note: "Đặc trưng bối cảnh VN, tránh dùng vật ngoại nhập.",
  },
  {
    id: 5, pillar: "P1",
    title: "Tiền Giấy Cổng Trường Bay Lên 3D",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Tờ tiền cờ tỷ phú giấy in lốm đốm màu (mua 5k ngoài cổng trường) làm stop motion. Tờ giấy bay lên, xoay vòng và biến thành hiệu ứng vàng bạc 3D rớt xuống bàn cờ mobile. Bridge giữa ký ức giấy và thế giới digital.",
    source: ["Gemini"],
    note: "Đặc trưng cổng trường VN thập niên 90–2000.",
  },
  {
    id: 6, pillar: "P1",
    title: "Sổ Tay / Thư Tay – Paper Stop Motion",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Giấy note, thư tay, hình dán, dấu mực, sticker dạ quang. Từng mẩu giấy 'bật' ra thành một scene game qua kỹ thuật stop motion. Không thoại, chỉ nhạc piano hoài niệm.",
    source: ["ChatGPT"],
    note: "Hợp để làm brand-safe creative cho mọi đối tượng.",
  },
  {
    id: 7, pillar: "P1",
    title: "Giao Diện Điện Thoại Qua Các Thế Hệ",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Biến hoá qua nhiều thế hệ điện thoại: Nokia cục gạch → Motorola flip → Sony Ericsson → iPhone 4 → smartphone hiện đại. Mỗi màn hình đều đang chạy game. Kết: 'Game này đi cùng thời mình lớn lên.' Nhấn mạnh sự bền bỉ của brand.",
    source: ["ChatGPT"],
    note: "Hướng đến audience đã trải qua nhiều thế hệ điện thoại (28–40 tuổi).",
  },
  {
    id: 8, pillar: "P1",
    title: "Băng VHS / TV Cũ – Analog Commercial",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Filter VHS, noise, khung hình cũ, chữ kiểu TV quảng cáo xưa. Toàn bộ ad được dựng như một đoạn quảng cáo trên TV thập niên 90–2000. Message: 'Đồ cổ nhưng không lỗi thời.' Chơi đùa hoàn toàn với aesthetic retro.",
    source: ["ChatGPT", "Gemini"],
    note: "ChatGPT gọi là Analog Commercial, Gemini làm chi tiết hơn với filter CRT và retro UI. Hợp nhất.",
  },
  {
    id: 9, pillar: "P1",
    title: "Tutorial Hướng Dẫn Giả Cổ VHS",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Video dạy học phong cách thập niên 90: filter VHS, giọng đọc trầm rè, hướng dẫn luật chơi phức tạp. Đột ngột cắt ngang: 'Nhưng bây giờ chỉ cần 1 chạm.' Màn hình điện thoại hiện game tự tính tiền. Message: Quên luật lệ phức tạp đi.",
    source: ["DeepSeek"],
    note: "Brief này tập trung vào contrast giữa sự phức tạp ngày xưa và UX đơn giản ngày nay.",
  },
  {
    id: 10, pillar: "P1",
    title: "Mùi Ký Ức – Social Experiment",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Cho Gen Z bịt mắt ngửi hộp bàn cờ cũ. Hỏi: 'Mùi gì?' Họ ngạc nhiên: 'Mùi... nhà bà ngoại lúc mưa.' Cut sang cả nhóm chơi Cờ Tỷ Phú trên iPad. Message: Cảm xúc còn đó, chỉ thiếu bộ cờ.",
    source: ["DeepSeek"],
    note: "Khai thác mùi như trigger ký ức — ít được dùng trong quảng cáo game.",
  },
  {
    id: 11, pillar: "P1",
    title: "Unboxing Hư Cấu – iPhone 4 Trong Hộp Carton",
    format: "Video – ASMR / Sound-led",
    formatTag: "VIDEO",
    desc: "Mở một hộp bìa carton cũ kỹ. Bên trong không phải bàn cờ giấy, mà là một chiếc iPhone 4 đời cũ đang bật màn hình game. 'Tinh hoa của 20 năm gói gọn trong 1 ứng dụng.' Kết hợp ASMR unboxing + twist bất ngờ.",
    source: ["DeepSeek"],
    note: "Concept surpresa: expectation vs reality của unboxing.",
  },
  {
    id: 12, pillar: "P1",
    title: "Đếm Tiền Giấy → Quét QR – Transition",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Tay đang đếm xấp tiền Cờ Tỷ Phú giả, đột nhiên giơ điện thoại quét mã QR ngay giữa bàn cờ để thanh toán tiền phạt. Transition mượt, không cắt cảnh. Message: Nhanh, gọn, không lằng nhằng.",
    source: ["DeepSeek"],
    note: "Khai thác sự đối lập hành vi analog vs digital trong cùng một ống kính.",
  },

  // ════════════════════════════════════════════════════
  // PILLAR 2: KÝ ỨC HỌC ĐƯỜNG & TUỔI THƠ
  // ════════════════════════════════════════════════════
  {
    id: 13, pillar: "P2",
    title: "Tan Học Là Giờ Chơi – Before/After Transition",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Từ cảnh đồng phục, cặp sách, sân trường → cảnh ngồi tụm lại chơi. Nhịp chuyển nhanh, vui, rất đời thường. Nhạc thay đổi hoàn toàn từ chuông trường sang nhạc vui. Hook: 'Hết giờ học là tới giờ chơi.'",
    source: ["ChatGPT"],
    note: "Short format, nhịp nhanh, hợp Reels/TikTok.",
  },
  {
    id: 14, pillar: "P2",
    title: "Quán Net / Tiệm Game – POV Cinematic",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Mở bằng cảnh bước vào quán net/tiệm game cũ: tiếng máy quạt, tiếng click, ánh đèn vàng, khói thuốc nhẹ. Chuyển mượt sang mở app Cờ Tỷ Phú như một 'cánh cổng quay về'. POV nhìn qua màn hình cũ.",
    source: ["ChatGPT", "Gemini"],
    note: "Gemini làm split-screen net cũ vs smartphone. ChatGPT dựng cinematic đơn. Hai hướng khác nhau nên giữ nguyên cả hai.",
  },
  {
    id: 15, pillar: "P2",
    title: "Quán Net Split-Screen 2010 vs 2026",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Màn hình chia đôi: nửa trên là màn hình lồi CRT, tay gõ phím cạch cạch ở tiệm net cũ. Nửa dưới là smartphone mượt mà chơi Cờ Tỷ Phú. Hook: 'Cảm giác làm trùm tài sản ngày ấy nay thu bé lại vừa bằng chiếc điện thoại.'",
    source: ["Gemini"],
    note: "Format split-screen phân biệt rõ với brief #14 ở ý tưởng so sánh hai thời đại.",
  },
  {
    id: 16, pillar: "P2",
    title: "Mùa Hè Nằm Bò Dưới Sàn – Super 8mm",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Quay cảnh chân trần, quạt mo cau quay chậm, nhóm bạn nằm bò dưới nền gạch bông. Hình ảnh ám vàng như phim nhựa cũ Super 8. Tiêu đề: 'Ký Ức Không Bụi Bặm.' Chuyển: Chơi online sạch sẽ mượt mà ở bất cứ đâu.",
    source: ["DeepSeek"],
    note: "Tone film, màu vintage đặc trưng. Không lời thoại.",
  },
  {
    id: 17, pillar: "P2",
    title: "Trốn Cô Giáo – Sách Giáo Khoa Khoét Rỗng",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Máy quay lia vào quyển sách Đại Số 8. Người chơi giả vờ chép bài nhưng lật sách ra — bên trong khoét rỗng đựng bàn cờ tí hon. Cảnh tiếp: Chuông reo. Cả lũ rút điện thoại ra 'phây' tiếp ván cờ trong giờ ra chơi.",
    source: ["DeepSeek"],
    note: "Sketch hài, execution đơn giản, chi phí thấp.",
  },
  {
    id: 18, pillar: "P2",
    title: "Mẹ Tịch Thu Bộ Cờ – Comedy Sketch",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Nhân vật đang đắc ý vì mua được Bến Ninh Kiều. Bóng mẹ dữ dằn xuất hiện, ném bộ cờ vào xó. Nhân vật quay sang thì thầm: 'May quá, game này mẹ không tịch thu được, vì nó trong điện thoại.' Khai thác ký ức bị phạt phổ biến của thế hệ 8x–9x.",
    source: ["DeepSeek", "ChatGPT"],
    note: "DeepSeek dùng bối cảnh mẹ, ChatGPT mở rộng sang cô giáo/sếp. Brief này giữ nguyên bối cảnh mẹ.",
  },
  {
    id: 19, pillar: "P2",
    title: "Bị Bắt Gặp Chơi Game – Nhiều Bối Cảnh",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Cô giáo, bố mẹ, sếp, anh chị lần lượt 'bắt quả tang' đang chơi. Mỗi lần là một sketch ngắn 5–7 giây, cắt liên tiếp. Thoại và biểu cảm là chìa khóa. 'Thời nào cũng có lúc phải chơi lén.' Format dễ viral nếu casting đúng.",
    source: ["ChatGPT"],
    note: "Phân biệt với #18: brief này là chuỗi nhiều bối cảnh, không chỉ mẹ.",
  },
  {
    id: 20, pillar: "P2",
    title: "Mẹo Gấp Bàn Cờ Trước Khi Cô Xuống",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Life hack video nhịp nhanh: cách gấp bàn cờ giấy siêu to khổng lồ vào hộc bàn trong 3 giây trước khi cô giáo xuống. Nhạc nền gấp gáp. Kết: 'Đỡ lằng nhằng hơn xưa. Mở máy ra là xong.' Format tutorial parody.",
    source: ["DeepSeek"],
    note: "Khác với brief gấp bàn cờ thông thường — yếu tố hài là 'deadline' gấp gáp.",
  },
  {
    id: 21, pillar: "P2",
    title: "Bản Tin Giờ Ra Chơi – Parody News",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Làm như bản tin nhanh, MC báo: 'Giờ chơi đã đến.' Thông báo kết quả ván cờ như tin thời sự. Có thể biến thành series ngắn nhiều tập. Hài hước nhẹ nhàng, quen thuộc với format tin tức VN.",
    source: ["ChatGPT"],
    note: "Series potential cao, mỗi tập là một tình huống game khác nhau.",
  },
  {
    id: 22, pillar: "P2",
    title: "Trailer Phim Học Đường Trận Cờ",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dựng trailer hoành tráng cho một trận chơi rất đời thường. Giọng đọc trailer deep, dramatic score, slow motion lật quân cờ. Càng 'làm lố' càng ra chất. Message: 'Mỗi ván cờ là một bộ phim.' Parody cinematic.",
    source: ["ChatGPT"],
    note: "Self-aware humor — biết mình đang dramatize chuyện nhỏ.",
  },
  {
    id: 23, pillar: "P2",
    title: "Ngày Mưa / Mất Điện – Mini Film",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Bối cảnh mưa, mất điện, tụ tập trong nhà. Ánh nến hắt lên mặt người. Game trở thành hoạt động cứu cánh nhưng mang cảm giác ấm áp. Kết: Đèn sáng trở lại — mọi người cúi xuống điện thoại chơi tiếp. Message: Cờ Tỷ Phú không cần chờ mất điện.",
    source: ["ChatGPT", "DeepSeek"],
    note: "ChatGPT là mood reel ngày mưa, DeepSeek là cinematic ánh nến. Gộp thành một brief giàu cảm xúc hơn.",
  },

  // ════════════════════════════════════════════════════
  // PILLAR 3: KÝ ỨC GIA ĐÌNH & BẠN BÈ
  // ════════════════════════════════════════════════════
  {
    id: 24, pillar: "P3",
    title: "Nhà Có 1 Điện Thoại – Family Comedy",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Cả nhà/anh em cùng chờ lượt, chuyền máy qua lại, tranh nhau nhưng cười. Khơi đúng cảm giác 'thời ít đồ chơi mà vui nhất.' Format sitcom gia đình ngắn 30–45 giây.",
    source: ["ChatGPT"],
    note: "Resonates mạnh với gia đình có 2–3 anh em thế hệ 8x–9x.",
  },
  {
    id: 25, pillar: "P3",
    title: "Anh Chị Em Tranh Lượt – Sitcom Sketch",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Anh chị em giành lượt, cà khịa nhau, nhưng kết bằng khoảnh khắc cùng cười. Khác với #24 — focus vào drama tranh chấp và kết hòa giải. Rất hợp nội dung share trên social vì ai cũng nhận ra mình trong đó.",
    source: ["ChatGPT"],
    note: "Phân biệt #24 (toàn gia đình chờ lượt) vs #25 (drama anh chị em).",
  },
  {
    id: 26, pillar: "P3",
    title: "Nhóm Bạn Thân – Chat Reenactment",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Format chat nhóm, từng tin nhắn kéo lại ký ức: 'Đêm nay chơi lại nha?' Dùng UI chat app quen thuộc (Zalo style). Cuối clip chốt bằng call-to-action mời bạn cũ. Cực kỳ relatable cho bất kỳ ai có nhóm bạn cũ.",
    source: ["ChatGPT"],
    note: "Format text-on-screen đơn giản, chi phí sản xuất thấp.",
  },
  {
    id: 27, pillar: "P3",
    title: "Bạn Đi Xa – Video Call Reaction",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "2 người bạn thân video call. Một đứa ở Sài Gòn, một đứa ở nước ngoài. 'Ê mày còn nhớ bàn cờ này không?' Cả hai cùng bấm 'Mời chơi'. Không cần bàn cờ, vẫn thấy nhau. Emotional nhẹ nhàng, không sến.",
    source: ["DeepSeek", "ChatGPT"],
    note: "DeepSeek có brief này rõ nét. ChatGPT cũng có brief về bạn cũ xa nhưng dạng montage. Đây là version video call cụ thể hơn.",
  },
  {
    id: 28, pillar: "P3",
    title: "Rủ Bạn Cũ Quay Lại – Reactivation",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Dành cho retargeting: tag bạn cũ, mời quay lại. Concept: không cần nói nhiều, chỉ cần ping nhau một lần. Visual đơn giản, text chủ đạo. Cảm giác 'Đã lâu rồi mình chưa chơi với nhau.' Nhắm người đã cài app nhưng inactive.",
    source: ["ChatGPT"],
    note: "Dành riêng cho retargeting audience, khác UGC thông thường.",
  },
  {
    id: 29, pillar: "P3",
    title: "Bạn Tụ Tập Vòng Tròn – Top Shot Overhead",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Góc quay từ trên xuống, nhiều người vây quanh điện thoại/tablet. Tay mọi người, tiếng cười, không thấy mặt ai. Cảm giác tụ tập rất 'hội'. Đây là visual khác biệt so với mọi game ad đang dùng góc thẳng.",
    source: ["ChatGPT"],
    note: "Góc quay overhead ít được dùng trong game ads — distinctive visual.",
  },
  {
    id: 30, pillar: "P3",
    title: "Ông Bà Học Chơi Game – TVC Cảm Động",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Ông nội cầm điện thoại hỏi cháu: 'Cái chữ Mua ở đâu con?' Cháu nhỏ phẩy tay. Ông tự mày mò. Một ngày, ông thách đấu cháu. Cả hai cười vang nhà. Message: Khoảng cách thế hệ xóa nhòa chỉ với một ván cờ. Phim ngắn 60–90 giây.",
    source: ["DeepSeek"],
    note: "Emotional brand film. Potential chạy Tết/Vu Lan.",
  },
  {
    id: 31, pillar: "P3",
    title: "Cô Cháu Gái Vô Tình Cướp Hết Tiền Bà",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Cô cháu gái diễn sâu: 'Bà ơi, bà hết tiền rồi, bà ra đảo ở đi.' Bà cười hiền: 'Ừ, bà bán cho con hết.' Cut cảnh hiện tại cô gái khóc huhu vì thấy tội. Message: Chơi online, không ai bị 'đuổi' ra đảo thật cả.",
    source: ["DeepSeek"],
    note: "Short skit dễ UGC, thoại tự nhiên.",
  },
  {
    id: 32, pillar: "P3",
    title: "Tết / Về Nhà – Seasonal Reunion Ad",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dịp lễ, Tết, gặp họ hàng/bạn cũ. Reconstruct cảnh Tết ngày xưa: nhà ngoại, mùi nhang, trẻ con được lì xì rồi rủ nhau chơi cờ. Game như 'cớ' để mọi người ngồi lại. Text: 'Tết này, ký ức đó quay lại.' Chạy trước dịp lễ.",
    source: ["ChatGPT", "Claude"],
    note: "Key seasonal asset. Cần sản xuất trước Tết ít nhất 6 tuần.",
  },
  {
    id: 33, pillar: "P3",
    title: "Dân Văn Phòng Giờ Nghỉ Trưa",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Dân văn phòng tranh thủ giờ nghỉ trưa mở game. Cảm giác 'ngày xưa chơi sau giờ học, giờ chơi sau giờ họp.' Visual: bàn làm việc, cà phê, áo vest. Contrast nhẹ nhàng với ký ức học đường.",
    source: ["ChatGPT"],
    note: "Nhắm audience 25–35 đang đi làm nhưng vẫn nhớ tuổi thơ.",
  },
  {
    id: 34, pillar: "P3",
    title: "Tình Bạn Phản Bội – Short Drama",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Kịch bản tình yêu tay ba lãng mạn nhưng nhân vật chính là các ông địa chủ. Một nhân vật bị 'cắm sừng' thương mại: 'Tao bán lại cho thằng kia rồi.' Transition: 'Chơi online với BOT, không lo bị phản bội.' Sketch hài, dramatic execution.",
    source: ["DeepSeek"],
    note: "Parody romance drama với chất liệu Cờ Tỷ Phú.",
  },
  {
    id: 35, pillar: "P3",
    title: "Suýt Cãi Nhau Vì Game – Mock Confession",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Nhân vật kể kiểu thú thật nhìn thẳng camera: 'Lúc đó tưởng giận mà thực ra vui.' Confession style, ánh sáng tự nhiên, một người. Liệt kê các lý do cãi nhau kinh điển: đổ xúc xắc rớt đất, tiền dư cuối ván ai lấy...",
    source: ["ChatGPT", "Claude"],
    note: "Format dễ UGC, authentic. Có thể làm KOC version.",
  },
  {
    id: 36, pillar: "P3",
    title: "Mock Team Trailer – Liên Minh Phe Phái",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dàn nhân vật kiểu 'đồng minh – đối thủ – người ngồi ngoài bình luận', dựng như trailer phim chiến đội nhưng nội dung là chơi vui. Giọng đọc trailer, hiệu ứng dramatic, slow-motion nhìn nhau. Humor từ sự tương phản.",
    source: ["ChatGPT"],
    note: "Format hài nhờ overdramatic execution cho chủ đề nhỏ.",
  },

  // ════════════════════════════════════════════════════
  // PILLAR 4: VĂN HÓA POP & RETRO TECH
  // ════════════════════════════════════════════════════
  {
    id: 37, pillar: "P4",
    title: "Yahoo Buzz Từ Crush – UI Animation",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Video mở bằng tiếng 'BUZZ!' của Yahoo Messenger rung bần bật màn hình. Tin nhắn từ crush cũ: 'Ê, làm ván cờ tỷ phú không?' Click vào link nhảy thẳng ra màn hình ingame. Sound design là key hero của brief này.",
    source: ["Gemini"],
    note: "Yahoo Buzz là âm thanh cực kỳ trigger với 8x–9x đầu.",
  },
  {
    id: 38, pillar: "P4",
    title: "Windows XP – Playable Interface Ad",
    format: "Playable Ad",
    formatTag: "PLAYABLE",
    desc: "User phải click chuột vào nút 'Start' màu xanh lá của Win XP, tìm icon Cờ Tỷ Phú để mở game. Màn hình mở ra là giao diện game cực hiện đại. Contrast giữa OS cổ và game mới. CTA: 'Chơi ngay bản nâng cấp.' Interactive ad format.",
    source: ["Gemini"],
    note: "Playable ad với giao diện Win XP — khai thác muscle memory của người dùng cũ.",
  },
  {
    id: 39, pillar: "P4",
    title: "Lịch Sử Duyệt Web IE – Static/GIF",
    format: "Banner / Static Image",
    formatTag: "BANNER",
    desc: "Giao diện trình duyệt Internet Explorer cũ kỹ. Khung search gõ: 'Cách để trở thành tỷ phú nhanh nhất.' Kết quả trả về là popup khổng lồ tải game Cờ Tỷ Phú. Format GIF ngắn hoặc static banner. Đơn giản, viral potential cao.",
    source: ["Gemini"],
    note: "GIF loop, không cần production cao. Social media native.",
  },
  {
    id: 40, pillar: "P4",
    title: "Băng Điện Tử 4 Nút NES – Thổi Phù",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Hành động 'thổi phù phù' vào cuộn băng game màu vàng để lau bụi, cắm vào máy. Màn hình TV lồi chớp tắt rồi hiện ra logo Cờ Tỷ Phú pixel art, sau đó transform thành đồ họa 3D hiện đại. 2D animation.",
    source: ["Gemini"],
    note: "Khai thác muscle memory thổi băng — ai cũng từng làm.",
  },
  {
    id: 41, pillar: "P4",
    title: "Rắn Săn Mồi Nokia → Bàn Cờ 3D",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Giao diện Nokia 1280 màn hình xanh đen. Con rắn bò ăn các chấm. Mỗi lần ăn được 1 chấm, nó biến thành 1 căn nhà/khách sạn trên bản đồ Cờ Tỷ Phú (chuyển dần từ 2D sang 3D màu). Gameplay mashup sáng tạo.",
    source: ["Gemini"],
    note: "Animation brief có concept mạnh, cần đội 2D/3D tốt.",
  },
  {
    id: 42, pillar: "P4",
    title: "Anime Battle – Triệu Hồi Xúc Xắc",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Nhân vật rút xúc xắc phong cách Yugioh cực cường điệu: hiệu ứng lửa cháy rực, góc máy gắt anime. Gieo ra số 6 kép. Bàn cờ nứt toác, nhà mọc lên như nấm. Thoát hoàn toàn bàn cờ tĩnh, tập trung vào visual effect.",
    source: ["Gemini"],
    note: "Nhắm audience có overlap với anime fandom.",
  },
  {
    id: 43, pillar: "P4",
    title: "Truyện Tranh Manga Dọc",
    format: "Carousel",
    formatTag: "CAROUSEL",
    desc: "Layout bài post dạng trang truyện tranh manga dọc (đọc phải sang trái). Khung 1: 'Ngươi định lấy hết tài sản của ta sao?' Khung 2: Nụ cười nửa miệng. Khung 3: 'Đổ xúc xắc đi!' Khung 4: Link/QR tải game. Black & white với accent màu đỏ.",
    source: ["Gemini"],
    note: "Carousel format khác biệt, đọc như truyện tranh thật.",
  },
  {
    id: 44, pillar: "P4",
    title: "Băng Cassette – Beat Sync Animation",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Nhét cuộn băng cassette vào đài radio cũ. Bấm Play. Giai điệu 8-bit cực bốc vang lên. Bàn cờ 'nhảy múa', các tòa nhà mọc lên theo từng nhịp beat (beat-sync animation). Năng lượng cao, vui.",
    source: ["Gemini"],
    note: "Music-driven, phù hợp chạy có audio on.",
  },
  {
    id: 45, pillar: "P4",
    title: "Dự Báo Thời Tiết 199X – Retro Parody",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Cô BTV thời tiết tóc xù, áo vest vai độn đứng chỉ tay vào bản đồ VN: 'Dự báo hôm nay sẽ có mưa nhà đất trên diện rộng, đặc biệt khu vực Hà Nội và TP.HCM tỷ lệ đổ xúc xắc trúng ô May Mắn cao kỷ lục.' Parody TV cũ hoàn chỉnh.",
    source: ["Gemini"],
    note: "Nếu casting đúng và costume chuẩn, viral potential rất cao.",
  },
  {
    id: 46, pillar: "P4",
    title: "AI Biến Ảnh 1999 Thành Hoạt Hình",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Dùng AI biến bức ảnh nhóm bạn chụp năm 1999 thành hoạt hình 3D đang chơi Cờ Tỷ Phú trên mây. Message: 'Ký ức đó giờ đã sống động.' Trend AI animation + nostalgia kép. Dễ UGC vì ai cũng có ảnh nhóm cũ.",
    source: ["DeepSeek"],
    note: "Leverage AI art trend hiện tại. Có thể làm UGC challenge.",
  },
  {
    id: 47, pillar: "P4",
    title: "Nhạc Thiếu Nhi Mashup – 5 Anh Em",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Beat remix bài hát thiếu nhi quen thuộc: '5 anh em trên một chiếc... ô tô nhựa.' Hình ảnh là 5 quân cờ xoay vòng quanh bàn cờ. Message: Kéo bạn bè vào chơi cho đủ team. Earworm + nostalgia combo.",
    source: ["DeepSeek"],
    note: "Chú ý bản quyền nhạc — có thể dùng bản nhạc inspired chứ không sample trực tiếp.",
  },
  {
    id: 48, pillar: "P4",
    title: "Trang Phục Đại Gia 90s – AI Fashion",
    format: "Banner / Static Image",
    formatTag: "BANNER",
    desc: "Dùng AI tạo ảnh các 'Đại Gia' trong game mặc áo bà ba, đeo dây chuyền vàng trơn, tay cầm điện thoại Nokia 8310. Phụ đề: 'Giàu từ kiếp trước.' Humor nhẹ nhàng, aesthetic kết hợp retro và in-game character.",
    source: ["DeepSeek"],
    note: "Static image / carousel. Chi phí thấp, dùng AI gen.",
  },
  {
    id: 49, pillar: "P4",
    title: "Voice-Over Thế Hệ Ba Mẹ – Character VO",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dùng giọng kể kiểu người lớn hồi tưởng (giọng ba/mẹ/chú/bác quen thuộc), nhưng visual trẻ trung và dynamic. Tương phản giọng già trầm với cảnh gameplay trẻ trung tạo độ dễ nhớ. Không nhất thiết cần diễn viên nổi tiếng.",
    source: ["ChatGPT"],
    note: "Audio contrast là yếu tố differentiating của brief này.",
  },
  {
    id: 50, pillar: "P4",
    title: "Zoom Xuyên Tờ Giấy Ô Ly Vào 3D City",
    format: "Video – POV / Action",
    formatTag: "VIDEO",
    desc: "Bàn cờ được vẽ tay nguệch ngoạc trên giấy ô ly bằng bút mực tím. Camera lao nhanh (zoom in) xuyên qua tờ giấy, phá vỡ mặt giấy và bước vào một thành phố 3D hoành tráng của Cờ Tỷ Phú ZingPlay. Epic transition.",
    source: ["Gemini"],
    note: "Cần production 3D, brief tốn kém hơn — chạy như hero creative.",
  },

  // ════════════════════════════════════════════════════
  // PILLAR 5: GAMEPLAY & CẢM XÚC KHI CHƠI
  // ════════════════════════════════════════════════════
  {
    id: 51, pillar: "P5",
    title: "Xúc Xắc Slow-Mo – Drama May Rủi",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Slow-motion xúc xắc lăn, dramatic score, mọi người nín thở. Số ra = kết quả cực kỳ dramatic. Khai thác bản năng mê may rủi của người Việt. Không cần giải thích luật chơi — cảm xúc là ngôn ngữ duy nhất của brief này.",
    source: ["Claude"],
    note: "Hook 3 giây đầu là xúc xắc lăn + silence.",
  },
  {
    id: 52, pillar: "P5",
    title: "Lật Kèo Từ 500k – Comeback Montage",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Gameplay clip: đang thua sát ván, còn 500k, cả bàn tưởng thua → đổ xúc xắc qua được 5 ô nguy hiểm, địch đạp vào bẫy → lật ngược hoàn toàn. Montage nhịp tăng dần. Pure gameplay, zero text. Hook: 'Chưa bao giờ hết hi vọng.'",
    source: ["ChatGPT", "Claude"],
    note: "Emotion arc: despair → tension → catharsis. Nhạc là critical element.",
  },
  {
    id: 53, pillar: "P5",
    title: "BLV Bình Luận Vào Tù – Sports Commentary",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "BLV hét vào micro như trận chung kết World Cup: 'VÀOOOOOO... TÙ GÌ KỲ VẬY TRỜI ƠI!' Đây là format câu view cho tình huống kém may mắn huyền thoại. Parody bình luận thể thao + drama Cờ Tỷ Phú.",
    source: ["DeepSeek"],
    note: "Short clip, BLV là hero. Cần voice actor giỏi.",
  },
  {
    id: 54, pillar: "P5",
    title: "Reaction Ăn May – Meme Biểu Cảm",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Phóng đại biểu cảm khi roll đẹp, trúng nhịp, thắng bất ngờ. Dễ làm UGC. Format: quay mặt người chơi từ trên xuống (phone camera). Text overlay tình huống. 'Tag người hay ăn may hơn mày.'",
    source: ["ChatGPT"],
    note: "UGC challenge potential — kêu gọi người dùng self-record reaction.",
  },
  {
    id: 55, pillar: "P5",
    title: "Cái Ô Ác Mộng – Shared Pain Reaction",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Highlight ô đất đắt nhất trong game. Người chơi đổ xúc xắc đúng ô đó, mặt chuyển từ tự tin sang hoảng loạn. Reaction style, authentic. 'Tag người hay làm mày đạp ô này.' Relatable pain = chia sẻ tự nhiên.",
    source: ["Claude"],
    note: "Comment bait ngầm: tag người gây ra nỗi đau.",
  },
  {
    id: 56, pillar: "P5",
    title: "Lật Bàn Slow Motion – Huyền Thoại",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Thanh niên cay cú vì phá sản, hất tung bàn cờ tung tóe (slow motion, nhạc Opera bi tráng). Thông điệp: 'Chơi mobile đi, lỡ cay thì tắt app chứ đừng đập điện thoại.' Humor từ drama quá lố.",
    source: ["Gemini"],
    note: "Overdramatic execution = humor. Slow-mo là bắt buộc.",
  },
  {
    id: 57, pillar: "P5",
    title: "Chiến Thuật Bí Mật – Expert Positioning",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "'Hầu hết mọi người nghĩ Cờ Tỷ Phú là may rủi. Sai.' → Reveal 3 chiến thuật thật: mua độc quyền màu, cầm tiền mặt tối thiểu, đầu tư đúng thời điểm. Nhắm người muốn cảm thấy thông minh hơn người khác.",
    source: ["Claude"],
    note: "Đánh vào ego của người chơi — ai cũng muốn là người biết chiến thuật.",
  },
  {
    id: 58, pillar: "P5",
    title: "Cuộc Chiến Ghế Ngân Hàng – Parody Game Show",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "MC hỏi: 'Ai là người gian lận nhiều nhất trong ván Cờ Tỷ Phú?' Đáp án: 'Luôn là đứa cầm Ngân Hàng.' Lồng ghép game: 'Chơi online, hệ thống làm nhà băng công bằng tuyệt đối.' Format parody quiz show.",
    source: ["DeepSeek"],
    note: "Ai cũng có ký ức về 'đứa cầm ngân hàng' gian lận.",
  },
  {
    id: 59, pillar: "P5",
    title: "Phân Tích Tội Phạm Học – Kẻ Gian Lận",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Giọng thuyết minh kiểu phá án: 'Nghi phạm luôn nhìn vào tủ lạnh khi đếm tiền, và tay phải luôn để dưới gối.' Kết luận: 'Nay chơi online, tay đâu giấu được nữa.' Format crime documentary parody.",
    source: ["DeepSeek"],
    note: "Khác #58 ở format: đây là documentary/true crime parody, không phải quiz show.",
  },
  {
    id: 60, pillar: "P5",
    title: "Infographic Giá Bất Động Sản 2000 vs 2025",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Hoạt hình: căn nhà ở Hàng Khay (bàn cờ cũ) giá 400 cành. So sánh với giá căn hộ 2025. Kết luận hài hước: 'Mua nhà ngoài đời khó quá, mua nhà trong Cờ Tỷ Phú cho đã tay.' Motion graphic đơn giản.",
    source: ["DeepSeek"],
    note: "Timely content — giá BĐS VN là chủ đề hot.",
  },
  {
    id: 61, pillar: "P5",
    title: "Hội 'Ghét Thằng May Mắn' – Streamer UGC",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Diễn viên đóng streamer bực mình: 'Sao nó đổ xúc xắc lúc nào cũng ra số to vậy?!' Giả lập livestream chat room náo loạn. Authentic, relatable với mọi người từng chơi game. UGC challenge: 'Show us your worst moment.'",
    source: ["DeepSeek"],
    note: "Format giả livestream đang trending, low production cost.",
  },
  {
    id: 62, pillar: "P5",
    title: "Tutorial Học Cờ 60 Giây – TikTok Style",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Gamified tutorial cực nhanh. Giải thích luật bằng visual metaphor: 'Đổ xúc xắc = di chuyển = nếu đất có chủ thì trả tiền. Đơn giản vậy thôi.' Nhắm audience chưa từng chơi bao giờ hoặc quên rồi. Nhịp nhanh, text lớn.",
    source: ["Claude"],
    note: "Acquisition creative cho cold audience.",
  },
  {
    id: 63, pillar: "P5",
    title: "POV Bên Trong Xúc Xắc – 3D Cinematic",
    format: "Video – POV / Action",
    formatTag: "VIDEO",
    desc: "Camera nằm trong viên xúc xắc trong suốt đang lăn lộn trên bàn gỗ học sinh (có khắc chữ, vết bút bi). Qua lớp nhựa trong suốt ta thấy bầu trời tuổi thơ. Khi xúc xắc dừng lại, kính vỡ ra, user rơi thẳng vào thế giới in-game. 3D macro cinematic.",
    source: ["Gemini"],
    note: "Hero creative — cần 3D production. Dùng làm opening brand video.",
  },
  {
    id: 64, pillar: "P5",
    title: "Máy Gắp Thú – Gắp Sổ Đỏ",
    format: "Playable Ad",
    formatTag: "PLAYABLE",
    desc: "Giao diện máy gắp thú bông ở siêu thị thời xưa. User điều khiển cần gạt để gắp 'Sổ đỏ' thay vì gấu bông. Gắp trúng → hiện nút tải game. Playable + nostalgia combo. Thời gian chơi thử 5–10 giây.",
    source: ["Gemini"],
    note: "Playable ad ít thấy trong game ads. Differentiated format.",
  },
  {
    id: 65, pillar: "P5",
    title: "Trò Đông Tây Nam Bắc → Ô Vào Tù",
    format: "Video – Skit / Hài",
    formatTag: "VIDEO",
    desc: "Bàn tay gấp tờ giấy Đông Tây Nam Bắc, mở ra trúng ô 'Vào Tù' hoặc 'Phá Sản'. Chuyển sang in-game lúc nhân vật dẫm phải ô thuế và cháy túi. Hook: 'Nhân phẩm từ nhỏ đến lớn vẫn vậy!' Relatable và hài hước.",
    source: ["Gemini"],
    note: "Short skit, prop chỉ cần tờ giấy.",
  },
  {
    id: 66, pillar: "P5",
    title: "ESPN Recap – Kể Lại Ván Cờ Epic",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Kể lại một ván cờ epic dạng ESPN recap: 'Ván này tôi suýt bỏ cuộc.' In-game footage, voice-over kể từng diễn biến như trận đấu thể thao. Biến game casual thành sử thi mini. Share-worthy vì có story arc thật.",
    source: ["Claude"],
    note: "Storytelling format — dài hơn thông thường (60–90s), dùng cho YouTube/Facebook.",
  },

  // ════════════════════════════════════════════════════
  // PILLAR 6: GIẢI CẤU TRÚC & TRIẾT LÝ
  // ════════════════════════════════════════════════════
  {
    id: 67, pillar: "P6",
    title: "Bàn Cờ 3D Ngoài Đời Thực – GoPro POV",
    format: "Video – POV / Action",
    formatTag: "VIDEO",
    desc: "GoPro gắn trên đầu diễn viên. Diễn viên bước đi trên bản đồ khổng lồ vẽ bằng phấn ngoài sân khu tập thể cũ. Khi đến ô Khí Vận, tay cầm điện thoại hiện lựa chọn Bốc Thăm. Đưa bàn cờ ra ngoài đời thực theo nghĩa đen.",
    source: ["DeepSeek"],
    note: "Production cần không gian rộng và phấn màu. Unique visual.",
  },
  {
    id: 68, pillar: "P6",
    title: "Vlog Triết Lý – Lòng Vòng Ô Bắt Đầu",
    format: "Video – UGC / Slice of Life",
    formatTag: "VIDEO",
    desc: "Người dẫn chuyện đi dạo Hồ Gươm. 'Có những ngày bạn chỉ lòng vòng Ô Bắt Đầu. Có ngày bạn lãnh thẻ Ra Tù. Đó là cuộc sống. Hãy cứ tung xúc xắc thôi.' Game như phản chiếu hành trình sống. Tone chữa lành.",
    source: ["DeepSeek"],
    note: "Tone 'chữa lành' đang trending trên TikTok VN. Brand safe.",
  },
  {
    id: 69, pillar: "P6",
    title: "Định Nghĩa Lại Phá Sản – Motivational",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Hình ảnh người đàn ông công sở mệt mỏi. 'Trong Cờ Tỷ Phú, phá sản là hết. Ngoài đời, phá sản là khởi đầu.' Lồng ghép game: 'Ở đây phá sản không đau, mở bàn mới chơi tiếp.' Vừa motivational vừa bán product benefit.",
    source: ["DeepSeek"],
    note: "Emotional reframe của failure — tone khác hẳn brief hài.",
  },
  {
    id: 70, pillar: "P6",
    title: "Bài Học Đời Qua Trò Chơi – Life Metaphor",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dùng game như ẩn dụ cho tiền bạc, rủi ro, cơ hội, lật kèo. Cảm giác trưởng thành nhưng vẫn mềm mại. Visual là người lớn chơi nhưng ký ức flash về trẻ con. Message ngầm: đây không chỉ là trò chơi.",
    source: ["ChatGPT"],
    note: "Phân biệt với #68: đây focus vào các bài học cụ thể từ cơ chế game.",
  },
  {
    id: 71, pillar: "P6",
    title: "Alternate Timeline – Giá Mà Hồi Đó Có",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Dựng bối cảnh quá khứ rồi đặt app vào đó như một điều ước. 'Giá mà hồi đó có cái này...' What-if narrative. Format mạnh vì đánh đúng hoài niệm. Có thể làm nhiều version khác nhau với các setting khác nhau.",
    source: ["ChatGPT"],
    note: "What-if framing tạo curiosity gap mạnh.",
  },
  {
    id: 72, pillar: "P6",
    title: "Bói Tarot Cho Người Chơi Cờ",
    format: "Video – Parody / Format Giả",
    formatTag: "VIDEO",
    desc: "Người xem bói lật lá 'The World' — trên lá bài là hình Bàn Cờ Tỷ Phú. 'Tháng này cơ hội mua đất của bạn rất cao, hãy cẩn thận tiền thuế.' Format tâm linh/horoscope parody. Hài nhẹ nhàng, share-worthy.",
    source: ["DeepSeek"],
    note: "Tận dụng trend tâm linh/tarot đang rất hot trên TikTok VN.",
  },
  {
    id: 73, pillar: "P6",
    title: "Hộp Thời Gian Từ Lớp 5",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Đào được hộp sắt chôn sau vườn từ năm lớp 5. Mở ra: bi ve, đĩa CD trầy, tấm thẻ 'Miễn vào tù' của bộ cờ. Dòng chữ hiện lên: 'Đã đến lúc dùng nó.' Cinematic, có emotional payoff tốt.",
    source: ["Gemini"],
    note: "Concept time capsule rất quen thuộc, dễ cảm xúc.",
  },
  {
    id: 74, pillar: "P6",
    title: "Monologue Ông Bắt Đầu – Tâm Thư",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Diễn viên kỳ cựu hóa trang thành Ông Bắt Đầu (người chia tiền). Ngồi nói chuyện với camera: 'Tao đã chia tiền cho chúng mày 20 năm nay rồi. Lớn cả rồi, tự vào app mà lấy.' Monologue xúc cảm kiểu phim độc lập.",
    source: ["DeepSeek"],
    note: "Anthropomorphizing game character — nhân vật hóa Ông Bắt Đầu.",
  },
  {
    id: 75, pillar: "P6",
    title: "Lái Xe Cub Gom Họ – POV Action",
    format: "Video – POV / Action",
    formatTag: "VIDEO",
    desc: "GoPro POV lái chiếc xe Cub 50 rẽ vào các con hẻm nhỏ Việt Nam. Chạy đến đâu, các ngôi nhà cấp 4 hai bên đường 'upgrade' thành Landmark 3D, tiền vàng văng vào màn hình. Thuần Việt, năng lượng cao.",
    source: ["DeepSeek"],
    note: "POV xe máy hẻm Sài Gòn + AR overlay — unique visual language.",
  },
  {
    id: 76, pillar: "P6",
    title: "Xây Nhà Time-lapse → 1 Chạm",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Quay cảnh thợ hồ trát vữa, xây gạch ống thật nhanh (time-lapse). Lồng tiếng: 'Xây 4 cái nhà lên thành 1 khách sạn.' Cut sang điện thoại: 'Hoặc chỉ cần 1 chạm để làm điều đó.' Dùng ngôn ngữ xây dựng thật.",
    source: ["DeepSeek"],
    note: "Grounding game mechanic bằng hình ảnh real-world familiar.",
  },
  {
    id: 77, pillar: "P6",
    title: "Phòng Ngủ 2004 – Dreamcore / Liminal Space",
    format: "Video – Cinematic / Phim Ngắn",
    formatTag: "VIDEO",
    desc: "Một phòng ngủ đậm chất 2004: poster ca sĩ Đan Trường, dán sticker dạ quang. Phòng trống không, chỉ có chiếc điện thoại trên giường đang sáng màn hình chạy auto Cờ Tỷ Phú. Aesthetic dreamcore/weirdcore — hoài niệm nhẹ ma mị.",
    source: ["Gemini"],
    note: "Niche format nhưng viral potential cao với niche audience Gen Z nostalgic.",
  },
  {
    id: 78, pillar: "P6",
    title: "Bầu Cua Tôm Cá × Cờ Tỷ Phú – Tết",
    format: "Video – Animation / Stop Motion",
    formatTag: "VIDEO",
    desc: "Mâm Bầu Cua Tết. Thay vì xóc ra con Nai, xúc xắc lăn ra Biệt Thự, Thẻ Miễn Phí, Ô Vào Tù. Sự kết hợp giữa cờ bạc truyền thống ngày Tết và cơ chế game. 3D animation, màu sắc tết.",
    source: ["Gemini"],
    note: "Seasonal Tết content. Kết hợp 2 cultural touchpoints mạnh.",
  },
  {
    id: 79, pillar: "P6",
    title: "Sớ Táo Quân – Bảng Xếp Hạng Đại Gia",
    format: "Banner / Static Image",
    formatTag: "BANNER",
    desc: "Cuộn sớ dài mở ra, ghi tên các 'Đại Gia' đang thống lĩnh bảng xếp hạng Cờ Tỷ Phú. Art style tranh Hàng Trống hoặc Đông Hồ nhưng vẽ buildings hiện đại. Static image cao cấp về mặt art direction.",
    source: ["Gemini"],
    note: "Art direction độc đáo, có thể làm thành series artwork.",
  },
  {
    id: 80, pillar: "P6",
    title: "Xin Xăm Đầu Năm – Playable Ad",
    format: "Playable Ad",
    formatTag: "PLAYABLE",
    desc: "Giao diện xin xăm ở đình làng đầu năm. Ống xăm rơi ra thẻ 'Đại Cát: Thu mua toàn bộ Landmark.' Chuyển cảnh in-game đang chiếm được mảng lớn trên bàn cờ. Playable + văn hóa dân gian + Tết.",
    source: ["Gemini"],
    note: "Playable ad seasonal — chạy dịp Tết/đầu năm âm lịch.",
  },
];

async function seedData() {
  console.log("Seeding data...");
  const updates = {};
  BRIEFS.forEach((b, i) => {
    const key = 'task_' + String(Date.now() + i).padStart(15, '0');
    updates[key] = {
      stt: i + 1,
      nguon: b.source.length === 0 ? 'Manual' : 'AI',
      aiNames: b.source.join(', '),
      insight: 'Nostalgia',
      concept: b.title || '(Tên concept)',
      format: b.format || 'Khác',
      description: b.desc || '',
      status: 'Draft',
      ready: false,
      pic: '',
      link: '',
      linkText: '',
      note: b.note || '',
      hidden: false,
      order: i + 1,
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
  });
  // use dbPatch on root or tasks
  // But our dbPatch expects a path. If we patch "tasks", it will merge.
  // Actually, wait, dbPatch does a PATCH.
  await dbPatch('tasks', updates);
  console.log("Seed done.");
}
